- name: install nginx and satrt nginx
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: install

  - name: start nginx
    ansible.builtin.service:
      name: nginx 
      state: started
      enabled: true


