- name: task level vars
  hosts: local
  connection: local
  vars:
    course: aws
    duration: 120hrs
    trainer: shiva
  tasks:
  - name: print course details
    vars:
      course:ansible
    ansible.builtin.debug:
      msg: "course details are: course name is: {{ course }}, duration: {{ duration }}, trainer: {{ trainer }}"
  
