- name: vars files
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print var files details
    ansible.builtin.debug:
     msg: "course details are: course name is: {{ course }}, duration: {{ duration }}, trainer: {{ trainer }}"
