- name: vars files
  hosts: local
  connection: local
  var_files:
  - course.yaml
  tasks:
  - name: print var files details
    ansible.builtin.debug:
     msg: "Course Name is: {{ COURSE }}, Duratioin: {{ DURATION }}, Trainer: {{ Trainer }}"
